version: "3.7"

services:
  toto:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ~/.ssh/gabriel:/root/.ssh
      - ./pages:/app/pages
      - ./deploy:/app/deploy
      - ./scripts:/app/scripts
      - ./public:/app/public
      - ./styles:/app/styles
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.toto.entrypoints=web"
      - "traefik.http.routers.toto.rule=Host(`idp.localhost`)"
